const RoleEnum = Object.freeze({
  TOWER_CONTROLLER: "TOWER_CONTROLLER",
  PILOT: "PILOT",
  GROUND_CREW: "GROUND_CREW",
  GATE_AGENT: "GATE_AGENT",
  AIRLINE_COMPANY_MANAGER: "AIRLINE_COMPANY_MANAGER",
  AIRPORT_ANALYST: "AIRPORT_ANALYST",
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
});

export default RoleEnum;
