<?php

/**
 * @brief Provides financial calculations for airport operations.
 *
 * This class contains constants and utility methods used to calculate
 * operational costs, revenues, and financial summaries over a specified
 * period of time.
 */
class FinanceSystem
{
    /**
     * @brief Daily cost required to operate the airport.
     */
    public const DAILY_COST=5000;

    /**
     * @brief Daily revenue generated by the airport.
     */
    public const DAILY_REVENUE=5500;

    /**
     * @brief Cost charged for each arriving flight.
     */
    public const LANDING_COST=100;

    /**
     * @brief Cost associated with each departing flight.
     */
    public const TAKING_OFF_COST=100;

    /**
     * @brief Revenue generated by each departing flight.
     */
    public const TAKING_OFF_REVENUE=250;

    /**
     * @brief Calculates airport operating costs within a time period.
     *
     * The calculation includes daily operating expenses as well as
     * costs associated with arriving and departing flights recorded
     * during the specified period.
     *
     * @param t1 Start date and time of the period.
     * @param t2 End date and time of the period.
     *
     * @return float Total airport costs for the selected period.
     */
    public static function calculateAirportCosts(String $t1, String $t2): float{
        require 'DatabaseInfo.php';
        try {
            $conn = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password);
            $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        } catch(PDOException $e){
            return 0;
        }
        try {
            $query=$conn->prepare("SELECT COUNT(*) AS 'n' FROM flights WHERE scheduled_time BETWEEN :t1 AND :t2 AND departure_airport_id=1 AND validation IN ('ACCEPTED','CONFIRMED') AND modify_id IS NULL");
            $query->bindParam(':t1',$t1);
            $query->bindParam(':t2',$t2);
            $query->execute();
            $result=$query->fetch();
            $tot=$result["n"]*self::TAKING_OFF_COST;

            $query=$conn->prepare("SELECT COUNT(*) AS 'n' FROM flights WHERE scheduled_time BETWEEN :t1 AND :t2 AND arrival_airport_id=1 AND validation IN ('ACCEPTED','CONFIRMED') AND modify_id IS NULL");
            $query->bindParam(':t1',$t1);
            $query->bindParam(':t2',$t2);
            $query->execute();
            $result=$query->fetch();
            $tot=$tot+$result["n"]*self::LANDING_COST;
            $tot=$tot+ (round((strtotime($t2)-strtotime($t1)) / (60 * 60 * 24))+1)*self::DAILY_COST;
            return $tot;
        } catch(PDOException $e) {
            return 0;
        }
    }

    /**
     * @brief Calculates airport revenue within a time period.
     *
     * The calculation includes daily airport revenue and revenue
     * generated by departing flights during the specified period.
     *
     * @param t1 Start date and time of the period.
     * @param t2 End date and time of the period.
     *
     * @return float Total airport revenue for the selected period.
     */
    public static function calculateAirportRevenue(String $t1, String $t2): float{
        require 'DatabaseInfo.php';
        try {
            $conn = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password);
            $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        } catch(PDOException $e){
            return 0;
        }
        try {
            $query=$conn->prepare("SELECT COUNT(*) AS 'n' FROM flights WHERE scheduled_time BETWEEN :t1 AND :t2 AND departure_airport_id=1 AND validation IN ('ACCEPTED','CONFIRMED') AND modify_id IS NULL");
            $query->bindParam(':t1',$t1);
            $query->bindParam(':t2',$t2);
            $query->execute();
            $result=$query->fetch();
            $tot=$result["n"]*self::TAKING_OFF_REVENUE;
            $tot=$tot+ (round((strtotime($t2)-strtotime($t1)) / (60 * 60 * 24))+1)*self::DAILY_REVENUE;
            return $tot;
        } catch(PDOException $e) {
            return 0;
        }
    }

    /**
     * @brief Generates a financial summary for a time period.
     *
     * Calculates total costs, total revenue, and net profit or loss
     * between the specified dates.
     *
     * @param t1 Start date and time of the period.
     * @param t2 End date and time of the period.
     *
     * @return array An array containing:
     *               - Total costs
     *               - Total revenue
     *               - Net result (revenue minus costs)
     */
    public static function getFinancialOverview(String $t1, String $t2): array{
        if(strtotime($t1)&&strtotime($t2)&&$t1<=$t2){
            $cost=self::calculateAirportCosts($t1,$t2);
            $revenue=self::calculateAirportRevenue($t1,$t2);
            $total=$revenue-$cost;
            return [$cost,$revenue,$total];
        }else
            return[0,0,0];
    }
}
?>

